public with sharing class Account {


public void m1(){

//First method 
}
public void m2(){

//second method 
}

 
public void m5(){

//fifth method
}

public void m7(){

//fifth method

//This push from MTS1
//This push from MTS1
//This push from MTS1
//This push from MTS1

//This push from MTS2
//This push from MTS2
//This push from MTS2
//This push from MTS2


//This push from MTS3
//This push from MTS3
//This push from MTS3
//This push from MTS3

//This push from MTS5
//This push from MTS5
//This push from MTS5
//This push from MTS5

//This push from MTS7
//This push from MTS7
//This push from MTS7
//This push from MTS7
}
}

